"""No ruta

Revision ID: a34389862536
Revises: 8faeba07ca8b
Create Date: 2025-05-08 23:47:19.548802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34389862536'
down_revision = '8faeba07ca8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagenes_pecl2', schema=None) as batch_op:
        batch_op.drop_column('ruta_imagen')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('imagenes_pecl2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ruta_imagen', sa.VARCHAR(length=500), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
